server:
  port: 8889
spring:
  r2dbc:
    url: r2dbc:pool:postgresql://127.0.0.1:5432/gzmu
    username: postgres
    password: 123456
oauth2:
  client:
    id: gzmu-auth
    secret: gzmu-auth-secret
    scopes: READ
    introspection-uri: http://127.0.0.1:8888/oauth/check_token