server:
  port: 8889
spring:
  r2dbc:
    url: r2dbc:pool:postgresql://118.24.1.170:5432/gzmu
    username: postgres
    password: 123456
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://118.24.1.170:8888/.well-known/jwks.json